[package]
name = "ssh-ed25519"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signature = "2.1.0"
ssh-key = { version = "0.6.0-rc.2", features = ["ed25519"] }
