[package]
name = "mylite-json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lite-json = "0.1.3"
lite-parser = "0.1.2"
