[package]
name = "myopentelemetry-otlp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = "0.16.0"
opentelemetry-otlp = "0.9.0"
